/* Canvas drawing avoids thousands of interactive SVG nodes while panning. */
(function(root){
'use strict';
if(!document.createElementNS)return;
const cloud=root.SiteCloud,G=root.SitePlan,page=document.getElementById('site-prd');
let drawing=null,loading=false,loadedUser=null,loadSerial=0;
const states=new Map(),names={steel:'철골보',slab:'슬래브'},colors=['#dae8f0','#e0ebe2','#e7e4f0','#efe8da'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const trade of ['steel','slab']){
 const pane=page.querySelector(`[data-trade="${trade}"]`);
 pane.innerHTML=`<p class="plan-load" role="status">도면을 불러올 준비를 하고 있습니다.</p><div class="plan-workspace" hidden><div class="plan-zones prd-zone-tabs" aria-label="${names[trade]} 공구 선택"></div><div class="plan-stats" aria-live="polite"></div><div class="plan-layout"><div class="plan-main card"><div class="plan-toolbar"><strong>지하2층 · ${names[trade]}</strong><button type="button" data-action="in" aria-label="도면 확대">＋</button><button type="button" data-action="out" aria-label="도면 축소">−</button><button type="button" data-action="fit">도면 맞춤</button><button type="button" data-action="graphs" aria-pressed="false">현황 그래프</button><button type="button" data-action="detail" aria-pressed="true">상세정보 닫기</button><button type="button" data-action="refresh">최신 기록</button>${trade==='steel'?'<label>표시<select data-plan-filter><option value="all">전체 선</option><option value="duplicates">중복 검토</option><option value="hideCompare">중복 비교선 숨김</option></select></label><label>비교 그룹<select data-plan-group aria-label="중복 비교 그룹"><option value="">그룹 선택</option></select></label>':'<label><input type="checkbox" data-plan-review>추가 검토 영역 표시</label>'}</div><canvas class="plan-map" tabindex="0" aria-label="${names[trade]} 도면 · 클릭하여 정보 입력 · 드래그 이동 · 휠 확대"></canvas><div class="plan-graphs" hidden></div><p class="plan-foot">${trade==='steel'?'파랑: 비교 기준선 · 자홍: 중복 비교선 · 회색: 일반 선. 비교선이 반드시 삭제 대상이라는 뜻은 아닙니다.':'색칠된 영역은 슬래브 폐곡선 후보입니다. 추가 검토 영역은 개구부 여부를 먼저 확인해 주세요.'}</p></div><aside class="plan-detail card"><h3>${trade==='steel'?'부재별':'영역별'} 시공 정보</h3><p class="plan-empty">도면을 클릭하면 정보를 입력할 수 있습니다.</p><form hidden><strong class="plan-title"></strong><p class="plan-status prd-muted"></p><dl class="plan-info"></dl><div class="plan-compare"></div><label>${trade==='steel'?'부재 번호':'구역 이름'}<input name="label" maxlength="120" placeholder="직접 입력"></label><label>${trade==='steel'?'부재 규격':'슬래브 사양'}<input name="spec" maxlength="120" placeholder="${trade==='steel'?'예: H-400×200×8×13':'예: 두께 150 mm'}"></label>${trade==='steel'?'<label>자재 반입일<input type="date" name="delivered"></label>':''}<label>${trade==='steel'?'설치 완료일':'타설일(완료일)'}<input type="date" name="completed"></label><label>메모<textarea name="note" maxlength="2000"></textarea></label><button type="submit" class="prd-primary">기록 저장</button><p class="plan-form-message" role="status" aria-live="polite"></p></form></aside></div></div>`;
 const s={trade,pane,zone:'',selected:null,view:null,frame:0,drag:null,dirty:false,busy:false,records:{},versions:new Map(),paths:new Map(),graphs:false,details:true};states.set(trade,s);
 s.canvas=pane.querySelector('canvas');s.ctx=s.canvas.getContext('2d');s.form=pane.querySelector('form');
 const q=sel=>pane.querySelector(sel);
 pane.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.zone!==undefined){await chooseZone(s,b.dataset.zone);return;}
  if(b.dataset.item){await select(s,b.dataset.item,true);return;}
  switch(b.dataset.action){case 'retry':await ensureLoaded();break;case 'in':zoom(s,.8);break;case 'out':zoom(s,1.25);break;case 'fit':fit(s);break;case 'graphs':s.graphs=!s.graphs;show(s);break;case 'detail':s.details=!s.details;show(s);break;case 'refresh':await refresh(s);break;}
 });
 s.form.addEventListener('input',()=>{s.dirty=true;});s.form.addEventListener('submit',e=>{e.preventDefault();save(s);});
 q('[data-plan-filter]')?.addEventListener('change',()=>paint(s));
 q('[data-plan-review]')?.addEventListener('change',async()=>{if(s.selected&&drawing.slabMap.get(s.selected)?.review&&!q('[data-plan-review]').checked){if(!await save(s,true)){q('[data-plan-review]').checked=true;return;}s.selected=null;s.form.hidden=true;q('.plan-empty').hidden=false;}paint(s);stats(s);});
 q('[data-plan-group]')?.addEventListener('change',async e=>{const group=drawing?.duplicateGroups.find(g=>g.id===e.target.value);if(group){q('[data-plan-filter]').value='duplicates';await select(s,group.reference,true);}});
 s.canvas.addEventListener('pointerdown',e=>{if(!drawing||!cloud.allowed()||e.button!==0)return;s.drag={id:e.pointerId,x:e.clientX,y:e.clientY,view:[...s.view],scale:transform(s).scale,moved:false};s.canvas.setPointerCapture(e.pointerId);});
 s.canvas.addEventListener('pointermove',e=>{const d=s.drag;if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>4)d.moved=true;s.view=[d.view[0]-dx/d.scale,d.view[1]+dy/d.scale,d.view[2],d.view[3]];paint(s);});
 s.canvas.addEventListener('pointerup',async e=>{const d=s.drag;s.drag=null;if(!d||!drawing||!cloud.allowed())return;if(s.canvas.hasPointerCapture(e.pointerId))s.canvas.releasePointerCapture(e.pointerId);if(!d.moved){const p=world(s,e),hits=G.hits(drawing,trade,p,8/transform(s).scale,s.zone,q('[data-plan-review]')?.checked);const h=hits.find(m=>trade!=='steel'||q('[data-plan-filter]').value!=='hideCompare'||m.duplicate_role!=='compare');if(h)await select(s,h.key);}});
 s.canvas.addEventListener('pointercancel',()=>{s.drag=null;});
 s.canvas.addEventListener('wheel',e=>{if(!drawing)return;e.preventDefault();zoom(s,e.deltaY<0 ? .88 : 1.14,world(s,e));},{passive:false});
 s.canvas.addEventListener('keydown',e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(s,.8);}if(e.key==='-'){e.preventDefault();zoom(s,1.25);}if(e.key==='0'){e.preventDefault();fit(s);}});
 new ResizeObserver(()=>paint(s)).observe(s.canvas);
}
function items(s){return s.trade==='steel'?drawing.members:drawing.slabs.filter(v=>!v.review||s.pane.querySelector('[data-plan-review]').checked);}
function scoped(s){return items(s).filter(v=>!s.zone||v.zone===s.zone);}
function lookup(s,key){return (s.trade==='steel'?drawing.memberMap:drawing.slabMap).get(key);}
function path(points,holes=[]){const p=new Path2D();for(const ring of [points,...holes]){if(!ring.length)continue;p.moveTo(...ring[0]);for(const xy of ring.slice(1))p.lineTo(...xy);p.closePath();}return p;}
function transform(s){const rect=s.canvas.getBoundingClientRect(),[x,y,w,h]=s.view||[0,0,1,1],scale=Math.min(rect.width/w,rect.height/h)||1;return {rect,scale,ox:(rect.width-w*scale)/2,oy:(rect.height-h*scale)/2,x,y,w,h};}
function world(s,e){const t=transform(s);return [t.x+(e.clientX-t.rect.left-t.ox)/t.scale,t.y+t.h-(e.clientY-t.rect.top-t.oy)/t.scale];}
function paint(s){if(!s.frame)s.frame=requestAnimationFrame(()=>{s.frame=0;draw(s);});}
function draw(s){if(!drawing||!s.view||s.pane.hidden||!cloud.allowed())return;const t=transform(s),ctx=s.ctx,dpr=Math.min(window.devicePixelRatio||1,2),w=Math.max(1,Math.round(t.rect.width*dpr)),h=Math.max(1,Math.round(t.rect.height*dpr));if(s.canvas.width!==w)s.canvas.width=w;if(s.canvas.height!==h)s.canvas.height=h;
 ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,t.rect.width,t.rect.height);ctx.fillStyle='#f9fbfc';ctx.fillRect(0,0,t.rect.width,t.rect.height);ctx.translate(t.ox-t.x*t.scale,t.oy+(t.y+t.h)*t.scale);ctx.scale(t.scale,-t.scale);
 const visible=b=>b[2]>=t.x&&b[0]<=t.x+t.w&&b[3]>=t.y&&b[1]<=t.y+t.h;
 if(s.trade==='slab')for(const [i,v] of drawing.slabs.entries()){if(!visible(v.bounds)||(v.review&&!s.pane.querySelector('[data-plan-review]').checked))continue;ctx.globalAlpha=s.zone&&v.zone!==s.zone ? .12 : 1;ctx.fillStyle=s.records[v.key]?.completed?'#66b693':v.review?'#fff0e5':colors[i%colors.length];ctx.fill(s.paths.get(v.key),'evenodd');ctx.strokeStyle=v.review?'#d57736':'#abc0cd';ctx.lineWidth=.6/t.scale;ctx.stroke(s.paths.get(v.key));}
 const filter=s.pane.querySelector('[data-plan-filter]')?.value;
 for(const v of drawing.members){if(!visible(v.bounds)||filter==='hideCompare'&&v.duplicate_role==='compare')continue;ctx.globalAlpha=s.zone&&v.zone!==s.zone ? .1 : filter==='duplicates'&&!v.duplicate_group ? .14 : 1;ctx.strokeStyle=s.trade==='slab'?'#90a3b3':v.duplicate_role==='compare'?'#d53d89':v.duplicate_role==='reference'?'#166ac5':s.records[v.key]?.completed?'#208869':v.kind==='girder'?'#926a48':'#738c9d';ctx.lineWidth=(s.trade==='steel'&&v.duplicate_group?2:1)/t.scale;ctx.beginPath();ctx.moveTo(...v.a);ctx.lineTo(...v.b);ctx.stroke();}
 ctx.globalAlpha=1;ctx.fillStyle='#455d71';for(const c of drawing.columns){ctx.beginPath();if(c.center){ctx.arc(...c.center,c.radius,0,Math.PI*2);ctx.fill();}else ctx.fill(c.path);}
 for(const z of drawing.zones){ctx.strokeStyle=s.zone===z.id?'#007a65':'#198b78';ctx.lineWidth=(s.zone===z.id?2.5:1.2)/t.scale;ctx.stroke(z.path);}
 const selected=s.selected&&lookup(s,s.selected);if(selected){ctx.strokeStyle='#142e43';ctx.lineWidth=4/t.scale;if(s.trade==='steel'){ctx.beginPath();ctx.moveTo(...selected.a);ctx.lineTo(...selected.b);ctx.stroke();}else ctx.stroke(s.paths.get(selected.key));}
 if(s.trade==='steel'&&filter==='duplicates'){for(const g of drawing.duplicateGroups){if(s.zone&&!g.keys.some(k=>drawing.memberMap.get(k)?.zone===s.zone))continue;ctx.save();ctx.translate(...g.center);ctx.scale(1,-1);ctx.fillStyle='#aa285f';ctx.font=`${12/t.scale}px sans-serif`;ctx.fillText(g.id,4/t.scale,-6/t.scale);ctx.restore();}}
 ctx.globalAlpha=1;
}
function fit(s,box=drawing?.bounds){if(!box)return;const [x,y,X,Y]=box,pad=Math.max(X-x,Y-y)*.045;s.view=[x-pad,y-pad,X-x+2*pad,Y-y+2*pad];paint(s);}
function zoom(s,factor,p){if(!s.view)return;const b=drawing.bounds,nw=Math.max((b[2]-b[0])/150,Math.min((b[2]-b[0])*1.5,s.view[2]*factor)),r=nw/s.view[2];p=p||[s.view[0]+s.view[2]/2,s.view[1]+s.view[3]/2];s.view=[p[0]-(p[0]-s.view[0])*r,p[1]-(p[1]-s.view[1])*r,nw,s.view[3]*r];paint(s);}
function show(s){s.pane.querySelector('.plan-detail').hidden=!s.details;s.pane.querySelector('.plan-layout').classList.toggle('plan-no-detail',!s.details);s.canvas.hidden=s.graphs;s.pane.querySelector('.plan-graphs').hidden=!s.graphs;const b=s.pane.querySelector('[data-action="graphs"]');b.textContent=s.graphs?'도면으로 돌아가기':'현황 그래프';b.setAttribute('aria-pressed',String(s.graphs));const detail=s.pane.querySelector('[data-action="detail"]');detail.textContent=s.details?'상세정보 닫기':'상세정보 열기';detail.setAttribute('aria-pressed',String(s.details));paint(s);}
function message(s,text,error=false){const n=s.pane.querySelector('.plan-form-message');n.textContent=text;n.classList.toggle('prd-error',error);}
function controls(s){for(const el of s.form.querySelectorAll('input,textarea,button'))el.disabled=s.busy||!cloud.canEdit();}
function stats(s){if(!drawing)return;const list=scoped(s),a=G.summary(list,s.records),unit=s.trade==='steel'?'선':'영역';s.pane.querySelector('.plan-stats').textContent=`${s.zone||'전체'} · ${a.total.toLocaleString()}${unit} · ${s.trade==='steel'?'설치':'타설'} 기록 ${a.completed}${unit} · 완료 기록률 ${a.percent.toFixed(1)}%${s.trade==='steel'?' · 중복 검토 '+drawing.duplicateGroups.filter(g=>g.keys.some(k=>!s.zone||drawing.memberMap.get(k)?.zone===s.zone)).length+'그룹':''}`;
 const graphs=s.pane.querySelector('.plan-graphs');graphs.innerHTML='<h3>공구별 '+names[s.trade]+' 현황</h3><p class="prd-muted">날짜가 입력된 도면 '+unit+' 기준입니다. 실제 발주 수량이나 공정표 대비 진행률은 아닙니다.</p>'+drawing.zones.map(z=>{const a=G.summary(items(s).filter(v=>v.zone===z.id),s.records);return `<button type="button" class="plan-zone-bar" data-zone="${esc(z.id)}"><strong>${esc(z.id)}</strong><span class="prd-bar-track"><span style="width:${a.percent}%"></span></span><span>${a.completed} / ${a.total}</span><span>${a.percent.toFixed(1)}%</span></button>`;}).join('');
 for(const b of s.pane.querySelectorAll('.plan-zones button'))b.setAttribute('aria-pressed',String(b.dataset.zone===s.zone));
}
async function chooseZone(s,zone){if(!drawing||s.busy||!await save(s,true))return;s.zone=zone;s.selected=null;s.form.hidden=true;s.pane.querySelector('.plan-empty').hidden=false;s.graphs=false;const z=drawing.zones.find(v=>v.id===zone);fit(s,z?G.bounds(z.points):drawing.bounds);stats(s);show(s);}
async function select(s,key,focus=false){if(!drawing||!cloud.allowed()||s.busy||!await save(s,true))return;const v=lookup(s,key);if(!v)return;s.selected=key;s.details=true;s.graphs=false;s.form.hidden=false;s.pane.querySelector('.plan-empty').hidden=true;const r=s.records[key]||{};s.pane.querySelector('.plan-title').textContent=r.label||v.display;s.pane.querySelector('.plan-status').textContent=r.completed?(s.trade==='steel'?'설치 완료':'타설 완료'):r.delivered?'자재 반입 기록':'완료일 미입력';
 const length=s.trade==='steel'?Math.hypot(v.b[0]-v.a[0],v.b[1]-v.a[1])/1000:null;s.pane.querySelector('.plan-info').innerHTML=[['공구',v.zone==='unassigned'?'미분류':v.zone],s.trade==='steel'?['도면 선 길이',length.toFixed(2)+' m']:['폐곡선 면적',v.area.toFixed(2)+' m²'],...(v.review?[['구분','개구부·미연결 여부 확인 필요']]:[])].map(([k,val])=>`<dt>${esc(k)}</dt><dd>${esc(val)}</dd>`).join('');
 const compare=s.pane.querySelector('.plan-compare');compare.innerHTML='';if(v.duplicate_group){const group=drawing.duplicateGroups.find(g=>g.id===v.duplicate_group),pairs=drawing.duplicatePairs.filter(p=>p.group===group.id);compare.innerHTML=`<div class="plan-dup-notice"><strong>${esc(group.id)} · 중복 삭제 검토</strong><p>최대 선 간격 ${group.max_gap_mm.toFixed(2)} mm${group.mixed_layers?' · 보/거더 레이어 혼합':''}</p><p>기준선은 길이가 가장 긴 선입니다. 삭제 대상은 확정하지 않았습니다.</p>${group.keys.map(k=>{const m=drawing.memberMap.get(k);return `<button type="button" data-item="${esc(k)}" aria-pressed="${k===key}">${esc(s.records[k]?.label||m.display)} · ${m.duplicate_role==='reference'?'비교 기준':'함께 비교'}</button>`;}).join('')}<small>${pairs.map(p=>`간격 ${p.gap_mm.toFixed(2)} mm / 겹친 길이 ${(p.overlap_mm/1000).toFixed(2)} m`).join('<br>')}</small></div>`;s.pane.querySelector('[data-plan-group]').value=group.id;}
 for(const field of ['label','spec','delivered','completed','note'])if(s.form.elements.namedItem(field))s.form.elements.namedItem(field).value=r[field]||'';
 message(s,cloud.canEdit()?'입력 후 저장하면 다른 사용자도 확인할 수 있습니다.':'조회 전용 계정입니다.');controls(s);
 if(focus){if(s.zone&&v.zone!==s.zone){s.zone=v.zone==='unassigned'?'':v.zone;stats(s);}const pts=s.trade==='steel'?[v.a,v.b]:v.points;fit(s,G.bounds(pts));const minimum=(drawing.bounds[2]-drawing.bounds[0])/100;if(s.view[2]<minimum){const center=s.trade==='steel'?[(v.a[0]+v.b[0])/2,(v.a[1]+v.b[1])/2]:[(s.view[0]+s.view[2]/2),(s.view[1]+s.view[3]/2)];s.view=[center[0]-minimum/2,center[1]-minimum/2,minimum,minimum];}}
 show(s);paint(s);
}
async function save(s,silent=false){if(s.busy)return false;if(!s.dirty||!s.selected)return true;const epoch=cloud.generation,key=s.selected;
 try{const value=G.record(Object.fromEntries(['label','spec','delivered','completed','note'].map(f=>[f,s.form.elements.namedItem(f)?.value||''])),s.trade);s.busy=true;controls(s);message(s,'서버에 저장하고 있습니다…');const row=await cloud.saveTrade(s.trade,key,value,s.versions.get(key)||0);if(epoch!==cloud.generation||!cloud.allowed())return false;s.records[key]=G.record(row,s.trade);s.versions.set(key,row.version);s.dirty=false;updateSelectedRecord(s);stats(s);paint(s);message(s,'서버에 저장했습니다.');return true;}catch(e){message(s,e.code?cloud.explain(e):e.message,true);return false;}finally{s.busy=false;controls(s);}}
function updateSelectedRecord(s){if(!s.selected||s.dirty)return;const v=lookup(s,s.selected),r=s.records[s.selected]||{};if(!v)return;for(const field of ['label','spec','delivered','completed','note'])if(s.form.elements.namedItem(field))s.form.elements.namedItem(field).value=r[field]||'';s.pane.querySelector('.plan-title').textContent=r.label||v.display;s.pane.querySelector('.plan-status').textContent=r.completed?(s.trade==='steel'?'설치 완료':'타설 완료'):r.delivered?'자재 반입 기록':'완료일 미입력';}
function rows(rows){for(const s of states.values()){s.records={};s.versions.clear();for(const row of rows)if(row.trade===s.trade&&lookup(s,row.item_key)){s.records[row.item_key]=G.record(row,s.trade);s.versions.set(row.item_key,row.version);}updateSelectedRecord(s);stats(s);paint(s);}}
async function refresh(s){if(s.busy||s.dirty&&!confirm('저장하지 않은 입력을 버리고 최신 기록을 불러올까요?'))return;const epoch=cloud.generation;s.busy=true;controls(s);try{const data=await cloud.planRecords();if(epoch!==cloud.generation||!cloud.allowed()||[...states.values()].some(v=>v!==s&&v.dirty))return;s.dirty=false;rows(data);message(s,'최신 기록을 불러왔습니다.');}catch(e){message(s,cloud.explain(e),true);}finally{s.busy=false;controls(s);}}
async function ensureLoaded(){if(!cloud.allowed())return false;if(drawing&&loadedUser===cloud.userId)return true;if(loading)return false;loading=true;const epoch=cloud.generation,serial=++loadSerial;
 try{const {document:doc,rows:records}=await cloud.loadPlan();if(serial!==loadSerial||epoch!==cloud.generation||!cloud.allowed())return false;drawing=G.prepare(doc.drawing);loadedUser=cloud.userId;for(const z of drawing.zones)z.path=path(z.points);for(const c of drawing.columns)if(c.points)c.path=path(c.points);
  for(const s of states.values()){s.pane.querySelector('.plan-load').hidden=true;s.pane.querySelector('.plan-workspace').hidden=false;s.pane.querySelector('.plan-zones').innerHTML=[['','전체 도면'],...drawing.zones.map(z=>[z.id,z.id])].map(([id,label])=>`<button type="button" data-zone="${esc(id)}" aria-pressed="${!id}">${esc(label)}</button>`).join('');if(s.trade==='steel')s.pane.querySelector('[data-plan-group]').innerHTML='<option value="">그룹 선택</option>'+drawing.duplicateGroups.map(g=>`<option value="${g.id}">${g.id} · ${g.max_gap_mm.toFixed(1)} mm</option>`).join('');else for(const v of drawing.slabs)s.paths.set(v.key,path(v.points,v.holes));fit(s);controls(s);}
  rows(records);return true;
 }catch(e){if(serial===loadSerial)for(const s of states.values()){const n=s.pane.querySelector('.plan-load');n.hidden=false;n.innerHTML='도면을 불러오지 못했습니다. <button type="button" data-action="retry">다시 불러오기</button>';}}finally{if(serial===loadSerial)loading=false;}
 return false;
}
function clear(){loadSerial++;loading=false;drawing=null;loadedUser=null;for(const s of states.values()){s.drag=null;s.view=null;s.records={};s.versions.clear();s.paths.clear();s.selected=null;s.zone='';s.dirty=false;s.form.reset();s.form.hidden=true;s.pane.querySelector('.plan-empty').hidden=false;s.pane.querySelector('.plan-title').textContent='';s.pane.querySelector('.plan-info').innerHTML='';s.pane.querySelector('.plan-compare').innerHTML='';s.pane.querySelector('.plan-graphs').innerHTML='';s.pane.querySelector('.plan-workspace').hidden=true;s.pane.querySelector('.plan-load').hidden=false;s.pane.querySelector('.plan-load').textContent='승인된 계정으로 로그인하면 도면을 불러옵니다.';s.ctx.clearRect(0,0,s.canvas.width,s.canvas.height);}}
document.addEventListener('site-auth-change',()=>{if(!cloud.allowed()||loadedUser&&loadedUser!==cloud.userId)clear();for(const s of states.values())controls(s);if(cloud.allowed()&&page.classList.contains('on'))for(const s of states.values())if(!s.pane.hidden)root.SitePlanUI.activate(s.trade);});
window.addEventListener('beforeunload',e=>{if([...states.values()].some(s=>s.dirty)){e.preventDefault();e.returnValue='';}});
setInterval(async()=>{if(document.hidden||!drawing||!cloud.allowed()||[...states.values()].some(s=>s.dirty||s.busy))return;const epoch=cloud.generation;try{const next=await cloud.planRecords();if(epoch===cloud.generation&&cloud.allowed()&&![...states.values()].some(s=>s.dirty||s.busy))rows(next);}catch{}},30000);
root.SitePlanUI={hasUnsaved:()=>[...states.values()].some(s=>s.dirty),beforeTradeChange:trade=>states.has(trade)?save(states.get(trade),true):Promise.resolve(true),async activate(trade){if(await ensureLoaded())show(states.get(trade));},async exportSnapshot(trade){const s=states.get(trade);if(!await ensureLoaded()||!await save(s,true))throw Error('저장되지 않은 입력이 있어 다운로드를 중단했습니다.');return {trade,items:structuredClone(scoped(s)),records:structuredClone(s.records),scope:s.zone||'전체',asOf:root.PRDDashboard.today(),duplicatePairs:structuredClone(drawing.duplicatePairs),duplicateGroups:structuredClone(drawing.duplicateGroups)};}};
})(globalThis);


