/* Geometry helpers for authenticated steel/slab drawings. No real site data. */
(function(root){
'use strict';
const contains=(x,y,points)=>root.PRDZones.contains(x,y,points);
function segmentDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
function bounds(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return [Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];}
function index(items,points){const cells=new Map(),size=5000;for(const item of items){item.bounds=bounds(points(item));const [x,y,X,Y]=item.bounds;for(let i=Math.floor(x/size);i<=Math.floor(X/size);i++)for(let j=Math.floor(y/size);j<=Math.floor(Y/size);j++){const key=i+':'+j;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(item);}}return {query(p,t=0){const found=new Set();for(let i=Math.floor((p[0]-t)/size);i<=Math.floor((p[0]+t)/size);i++)for(let j=Math.floor((p[1]-t)/size);j<=Math.floor((p[1]+t)/size);j++)for(const v of cells.get(i+':'+j)||[])found.add(v);return [...found];}};}
function prepare(drawing){const members=drawing.members.map((m,i)=>({...m,display:(m.kind==='girder'?'거더 ':'보 ')+String(i+1).padStart(4,'0')})),slabs=drawing.slabs.map((s,i)=>({...s,display:(s.review?'검토 영역 ':'슬래브 ')+String(i+1).padStart(4,'0')}));return {...drawing,members,slabs,memberIndex:index(members,m=>[m.a,m.b]),slabIndex:index(slabs,s=>s.points),memberMap:new Map(members.map(m=>[m.key,m])),slabMap:new Map(slabs.map(s=>[s.key,s]))};}
function hits(drawing,trade,p,tolerance,zone='',review=false){if(trade==='steel')return drawing.memberIndex.query(p,tolerance).filter(m=>(!zone||m.zone===zone)&&segmentDistance(p,m.a,m.b)<=tolerance).sort((a,b)=>segmentDistance(p,a.a,a.b)-segmentDistance(p,b.a,b.b));return drawing.slabIndex.query(p).filter(s=>(!zone||s.zone===zone)&&(review||!s.review)&&contains(...p,s.points)&&!s.holes.some(h=>contains(...p,h))).sort((a,b)=>a.area-b.area);}
function record(value,trade){const r={label:String(value?.label||'').trim(),spec:String(value?.spec||'').trim(),delivered:trade==='steel'?String(value?.delivered||''):'',completed:String(value?.completed||''),note:String(value?.note||'')};if(r.label.length>120||r.spec.length>120||r.note.length>2000)throw Error('입력 길이를 확인해 주세요.');for(const k of ['delivered','completed'])if(r[k]){const d=new Date(r[k]+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(r[k])||r[k].startsWith('0000')||!Number.isFinite(+d)||d.toISOString().slice(0,10)!==r[k])throw Error('유효한 날짜를 입력해 주세요.');}if(r.delivered&&r.completed&&r.completed<r.delivered)throw Error('설치일은 자재 반입일보다 빠를 수 없습니다.');return r;}
function summary(items,records){let completed=0,delivered=0;for(const v of items){if(records[v.key]?.completed)completed++;if(records[v.key]?.delivered)delivered++;}return {total:items.length,completed,delivered,remaining:items.length-completed,percent:items.length?100*completed/items.length:0};}
root.SitePlan={prepare,hits,record,summary,bounds,segmentDistance};if(typeof module!=='undefined')module.exports=root.SitePlan;
})(globalThis);
