/* Geometry helpers for authenticated steel/slab drawings. No real site data. */
(function(root){
'use strict';
const A=root.SiteSlabArea||(typeof require==='function'?require('./site-slab-area.js'):null);
const contains=(x,y,points)=>root.PRDZones.contains(x,y,points);
function segmentDistance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],l=dx*dx+dy*dy,t=l?Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/l)):0;return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);}
function bounds(points){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return [Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];}
function index(items,points){const cells=new Map(),size=5000;for(const item of items){item.bounds=bounds(points(item));const [x,y,X,Y]=item.bounds;for(let i=Math.floor(x/size);i<=Math.floor(X/size);i++)for(let j=Math.floor(y/size);j<=Math.floor(Y/size);j++){const key=i+':'+j;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(item);}}return {query(p,t=0){const found=new Set();for(let i=Math.floor((p[0]-t)/size);i<=Math.floor((p[0]+t)/size);i++)for(let j=Math.floor((p[1]-t)/size);j<=Math.floor((p[1]+t)/size);j++)for(const v of cells.get(i+':'+j)||[])found.add(v);return [...found];}};}
const kindName=kind=>({beam:'작은보',girder:'큰보',sps:'SPS 철골보'}[kind]||'보');
function backgroundBatches(objects){const batches=new Map();for(const object of objects){const b=object.center?[object.center[0]-object.radius,object.center[1]-object.radius,object.center[0]+object.radius,object.center[1]+object.radius]:bounds(object.points);const key=Math.floor((b[0]+b[2])/40000)+':'+Math.floor((b[1]+b[3])/40000);let batch=batches.get(key);if(!batch){batch={bounds:[...b],objects:[]};batches.set(key,batch);}else batch.bounds=[Math.min(b[0],batch.bounds[0]),Math.min(b[1],batch.bounds[1]),Math.max(b[2],batch.bounds[2]),Math.max(b[3],batch.bounds[3])];batch.objects.push(object);}return [...batches.values()];}
function prepare(drawing){const members=drawing.members.map((m,i)=>({...m,display:'보 '+String(i+1).padStart(4,'0')})),slabs=drawing.slabs.map((s,i)=>({...s,display:s.display||(s.review?'검토 영역 ':'슬래브 ')+String(i+1).padStart(4,'0')})),zones=drawing.zones.map(z=>({...z,center:root.PRDZones.center(z.points)}));return {...drawing,bounds:drawing.perimeter?.length?bounds(drawing.perimeter):drawing.bounds,zones,members,slabs,backgroundBatches:backgroundBatches(drawing.background||[]),memberIndex:index(members,m=>[m.a,m.b]),slabIndex:index(slabs,s=>(s.parts||[s]).flatMap(p=>p.points)),memberMap:new Map(members.map(m=>[m.key,m])),slabMap:new Map(slabs.map(s=>[s.key,s]))};}
function zoneHit(drawing,p,tolerance,labelSize){for(const z of drawing.zones){const [x,y]=z.center;if(Math.abs(p[0]-x)<=labelSize*.75&&p[1]>=y-labelSize*.35&&p[1]<=y+labelSize*.95)return z.id;}for(const z of drawing.zones)for(let i=0;i<z.points.length;i++)if(segmentDistance(p,z.points[i],z.points[(i+1)%z.points.length])<=tolerance)return z.id;return '';}
function itemColor(trade,item,record,reviewMode=false){if(trade==='slab'){const fill={deck:'#dcebf6',conventional:'#ede7dc',temporary:'#e7e0f0',opening:'#ffffff'}[A.kind(record)];return fill||(record?.completed?'#66b693':item.review?'#fff0e5':'#dce5eb');}if(reviewMode&&item.duplicate_role==='compare')return '#d53d89';if(reviewMode&&item.duplicate_role==='reference')return '#166ac5';return record?.completed?'#009b60':'#738c9d';}
function hits(drawing,trade,p,tolerance,zone='',review=false){if(trade==='steel')return drawing.memberIndex.query(p,tolerance).filter(m=>(!zone||m.zone===zone)&&segmentDistance(p,m.a,m.b)<=tolerance).sort((a,b)=>segmentDistance(p,a.a,a.b)-segmentDistance(p,b.a,b.b));return drawing.slabIndex.query(p).filter(s=>(!zone||s.zone===zone)&&(review||!s.review)&&(s.parts||[s]).some(v=>contains(...p,v.points)&&!(v.holes||[]).some(h=>contains(...p,h)))).sort((a,b)=>a.area-b.area);}
function record(value,trade){const r={label:String(value?.label||'').trim(),spec:String(value?.spec||'').trim(),delivered:trade==='steel'?String(value?.delivered||''):'',completed:String(value?.completed||''),note:String(value?.note||'')};if(r.label.length>120||r.spec.length>120||r.note.length>2000)throw Error('입력 길이를 확인해 주세요.');if(trade==='slab'){r.slab_kind=String(value?.slab_kind||'opening');r.decked=String(value?.decked||'');r.reinforced=String(value?.reinforced||'');if(!['','deck','conventional','temporary','opening'].includes(r.slab_kind))throw Error('슬래브 종류를 확인해 주세요.');}for(const k of ['delivered','completed','decked','reinforced'])if(r[k]){const d=new Date(r[k]+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(r[k])||r[k].startsWith('0000')||!Number.isFinite(+d)||d.toISOString().slice(0,10)!==r[k])throw Error('유효한 날짜를 입력해 주세요.');}if(r.delivered&&r.completed&&r.completed<r.delivered)throw Error('설치일은 자재 반입일보다 빠를 수 없습니다.');if(trade==='slab'){for(const [a,b] of [['decked','reinforced'],['decked','completed'],['reinforced','completed']])if(r[a]&&r[b]&&r[a]>r[b])throw Error('데크 판개일 → 철근 설치일 → 타설일 순서를 확인해 주세요.');}return r;}
function activeMembers(members,visibility={}){return members.filter(v=>!visibility[v.key]?.hidden);}
function summary(items,records){let completed=0,delivered=0;for(const v of items){if(records[v.key]?.completed)completed++;if(records[v.key]?.delivered)delivered++;}return {total:items.length,completed,delivered,remaining:items.length-completed,percent:items.length?100*completed/items.length:0};}
// Namespace floor keys so identical member keys never share records or visibility.
function floorSources(plans){const steel={items:[],records:{},visibility:{},zoneIds:[]},slab={records:{},zoneIds:[]},areas=[],zoneAreas={};let slabReady=false;const slabItems=[];
 for(const plan of plans){const prefix=plan.id+':',d=plan.drawing,rows=plan.records||[];steel.zoneIds.push(...d.zones.map(z=>z.id));slab.zoneIds.push(...d.zones.map(z=>z.id));steel.items.push(...d.members.map(v=>({key:prefix+v.key,zone:v.zone})));for(const [key,value] of Object.entries(plan.visibility||{}))steel.visibility[prefix+key]=value;
  if(d.slabsReady!==false){slabReady=true;slabItems.push(...d.slabs.map(v=>({key:prefix+v.key,zone:v.zone})));const records=Object.fromEntries(rows.filter(r=>r.trade==='slab').map(r=>[r.item_key,r])),result=A.summarize(d.zones,d.slabs,records);areas.push(result.area);for(const [id,area] of Object.entries(result.byZone))(zoneAreas[id]??=[]).push(area);}
  for(const row of rows){if(row.trade==='steel')steel.records[prefix+row.item_key]=row;else if(row.trade==='slab'&&d.slabsReady!==false)slab.records[prefix+row.item_key]=row;}
 }if(slabReady){slab.items=slabItems;slab.area=A.aggregate(areas);slab.areaByZone=Object.fromEntries(Object.entries(zoneAreas).map(([id,values])=>[id,A.aggregate(values)]));}return {steel,slab};}
root.SitePlan={floorSources,prepare,hits,record,summary,activeMembers,bounds,segmentDistance,zoneHit,itemColor,kindName,backgroundBatches};if(typeof module!=='undefined')module.exports=root.SitePlan;
})(globalThis);
