const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../seismic.js');
function input(){return {zone:'I',hazardMode:'map',mapS:.17,importance:'I',soil:'S4',depthMode:'known',depth:30,vs:258.7627014609521,height:62.3,weight:499540.77,correction:true,x:{system:'1-b',periodType:'other',periodMode:'analysis',period:2.579,infill:false,Vt:10605.1},y:{system:'1-b',periodType:'other',periodMode:'analysis',period:2.477,infill:false,Vt:10948.56}};}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9*Math.max(1,Math.abs(b)),`${a} != ${b}`);
test('KDS workbook Seismic example matches its independently cached outputs',()=>{const r=E.calculate(input());assert.equal(r.valid,true);near(r.S,.176);near(r.Fa,1.448);near(r.Fv,2.048);near(r.SDS,.42474666666666666);near(r.SD1,.2402986666666667);near(r.x.Ta,1.0821459963160385);near(r.x.cap,1.5796099536838497);near(r.x.Cs,.045637595427832016);near(r.x.V,22797.839560967685);near(r.x.Cm,1.8272494956975918);near(r.y.Cm,1.7699280660490997);assert.equal(r.x.limitOK,false);});
test('Cu interpolation includes exact endpoints and interior values without extrapolation',()=>{for(const [s,c] of [[.01,1.7],[.1,1.7],[.125,1.65],[.15,1.6],[.175,1.55],[.2,1.5],[.25,1.45],[.3,1.4],[.4,1.4],[1,1.4]])near(E.interpolate(s,[[.1,1.7],[.15,1.6],[.2,1.5],[.3,1.4],[.4,1.4]]),c);});
test('zone uses full 2Z unless map mode is explicitly selected',()=>{let p=input();p.hazardMode='zone';near(E.calculate(p).S,.22);p.zone='II';near(E.calculate(p).S,.14);p.hazardMode='map';p.mapS=.1;near(E.calculate(p).S,.112);p.mapS=.18;near(E.calculate(p).S,.18);});
test('soil adjustment strict depth and inclusive velocity boundaries',()=>{let p=input();p.depth=20;p.vs=360;let r=E.calculate(p);near(r.Fv,r.baseFv);p.depth=20.01;r=E.calculate(p);near(r.Fv,.8*r.baseFv);p.vs=359.99;r=E.calculate(p);near(r.Fv,r.baseFv);p.soil='S5';p.depthMode='unknown';r=E.calculate(p);near(r.Fa,1.1*r.baseFa);near(r.Fv,1.1*r.baseFv);});
test('spectral curve is continuous at T0, Ts and TL and retains the 1/T² tail',()=>{const r=E.calculate(input());near(E.spectrum(0,r),.4*r.SDS);near(E.spectrum(r.T0,r),r.SDS);near(E.spectrum(r.Ts,r),r.SDS);near(E.spectrum(5,r),r.SD1/5);near(E.spectrum(10,r),r.SD1*5/100);for(const t of [r.T0,r.Ts,5])assert.ok(Math.abs(E.spectrum(t-1e-8,r)-E.spectrum(t+1e-8,r))<1e-6);});
test('category thresholds use both periods and importance without rounding',()=>{assert.equal(E.category(.169999,.069999,'I').governing,'A');assert.equal(E.category(.17,.01,'I').governing,'B');assert.equal(E.category(.33,.01,'I').governing,'C');assert.equal(E.category(.5,.01,'I').governing,'D');assert.equal(E.category(.01,.14,'special').governing,'D');assert.equal(E.category(.01,.2,'II').governing,'D');});
test('analysis period can be shorter than Ta; approximate mode does not use CuTa',()=>{let p=input();p.x.period=.2;let r=E.calculate(p);near(r.x.T,.2);p.x.periodMode='approx';p.x.period=NaN;r=E.calculate(p);near(r.x.T,r.x.Ta);p.x.periodType='rc';p.x.infill=true;r=E.calculate(p);near(r.x.Ta,.0466*p.height**.9*2/3);});
test('Cs uses period cap, long-period limit and minimum; axes remain independent',()=>{const p=input();p.height=500;p.x.period=6;p.y.period=.01;const r=E.calculate(p);near(r.x.periodTerm,r.SD1*r.IE/4*5/36);near(r.x.Cs,Math.max(.044*r.SDS*r.IE,.01,Math.min(r.x.plateau,r.x.periodTerm)));near(r.y.Cs,r.y.plateau);assert.notEqual(r.x.V,r.y.V);});
test('Cm never reduces and invalid dynamic values cannot display stale results',()=>{let p=input();p.x.Vt=1e6;near(E.calculate(p).x.Cm,1);p.x.Vt=0;assert.equal(E.calculate(p).valid,false);p.correction=false;p.y.Vt=NaN;let r=E.calculate(p);assert.equal(r.valid,true);assert.equal(r.x.Cm,null);p.soil='S6';assert.equal(E.calculate(p).valid,false);p=input();p.mapS=.31;assert.equal(E.calculate(p).valid,false);p=input();p.weight=NaN;assert.equal(E.calculate(p).valid,false);});
test('2022 system table includes updated interaction factor and height limits',()=>{assert.equal(E.SYSTEMS.length,60);assert.equal(new Set(E.SYSTEMS.map(s=>s.id)).size,60);assert.equal(E.SYSTEMS.find(s=>s.id==='7').omega,2.5);assert.equal(E.SYSTEMS.find(s=>s.id==='3-j').limits[2],30);const p=input();p.height=60;assert.equal(E.calculate(p).x.limitOK,true);p.x.system='1-d';assert.equal(E.calculate(p).x.limitOK,false);});
