const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function harness(){const listeners={};let allowed=true,generation=1,resolveRecords=null,fail=false,calls=0;const make=()=>({innerHTML:'',textContent:'',disabled:false,addEventListener(){}});const pages=['site-prd','site-north-prd'].map(id=>{const nodes={'[data-overview-body]':make(),'[data-overview-status]':make(),'[data-overview-refresh]':make()};const pane={hidden:false,querySelector:s=>nodes[s],addEventListener(){}};return {id,nodes,classList:{contains:()=>true},querySelector:s=>s==='[data-trade="overview"]'?pane:nodes[s]};});const cloud={allowed:()=>allowed,get generation(){return generation;},records:async()=>{calls++;if(fail)throw Error('offline');if(resolveRecords!==null)return new Promise(r=>resolveRecords=r);return [{pile_key:'p',installed:'2026-10-02'}];},planState:async()=>{calls++;return {records:[],visibility:{}};}};const context=vm.createContext({document:{createElementNS(){},querySelectorAll:()=>pages,addEventListener:(key,fn)=>listeners[key]=fn},SiteCloud:cloud,SiteOverview:require('../site-overview.js'),PRDDashboard:{today:()=> '2026-10-02'},PRDCloudUI:{overviewSnapshot:async()=>({items:[{key:'p',zone:'A1'}],zoneIds:['A1']})},SitePlanUI:{overviewSnapshot:async()=>({sources:{steel:{items:[{key:'B1:b',zone:'A1'},{key:'B2:b',zone:'A1'}],records:{'B2:b':{completed:'2026-10-02'}},zoneIds:['A1']},slab:{items:[],records:{},zoneIds:['A1']}},coverage:'철골보 지하1층·지하2층 합산'})},setInterval(){},structuredClone});vm.runInContext(fs.readFileSync(require.resolve('../site-overview-ui.js'),'utf8'),context);return {context,pages,cloud,get calls(){return calls;},hold(){resolveRecords=true;},release(){resolveRecords([]);},logout(){allowed=false;generation++;listeners['site-auth-change']();},fail(){fail=true;}};}
test('south overview uses both floor records and displays the aggregation scope',async()=>{
 const h=harness();await h.context.SiteOverviewUI.activate(h.pages[0]);
 const html=h.pages[0].nodes['[data-overview-body]'].innerHTML;
 assert.match(html,/철골보 지하1층·지하2층 합산/);assert.match(html,/50\.0%/);
});
test('steel overview shows confirmed installation totals without a completion date',async()=>{
 const h=harness();h.context.SitePlanUI.overviewSnapshot=async()=>({sources:{steel:{items:[{key:'a',zone:'A3'},{key:'b',zone:'A3'}],records:{a:{installation_complete:true},b:{installation_complete:true}}}},coverage:'지하2층'});
 await h.context.SiteOverviewUI.activate(h.pages[0]);const html=h.pages[0].nodes['[data-overview-body]'].innerHTML;
 assert.match(html,/설치 완료 확인 기준/);assert.match(html,/<b>2<\/b> \/ 2부재 · 설치 완료/);assert.match(html,/100\.0%/);
});
test('north overview never reads southern records and uses pending data instead of fake zeroes',async()=>{const h=harness();await h.context.SiteOverviewUI.activate(h.pages[1]);assert.equal(h.calls,0);assert.match(h.pages[1].nodes['[data-overview-body]'].innerHTML,/북측/);assert.match(h.pages[1].nodes['[data-overview-body]'].innerHTML,/집계 준비 중/);assert.doesNotMatch(h.pages[1].nodes['[data-overview-body]'].innerHTML,/0\.0%/);});
test('auth revocation clears rendered progress and prevents a pending response from restoring private content',async()=>{const h=harness();await h.context.SiteOverviewUI.activate(h.pages[0]);assert.match(h.pages[0].nodes['[data-overview-body]'].innerHTML,/100\.0%/);h.hold();const pending=h.context.SiteOverviewUI.activate(h.pages[0]);await new Promise(r=>setImmediate(r));h.logout();h.release();await pending;assert.equal(h.pages[0].nodes['[data-overview-body]'].innerHTML,'');await assert.rejects(h.context.SiteOverviewUI.exportSnapshot(h.pages[0]),/권한/);});
test('failed refresh visibly marks stale figures and cannot export them as a fresh overview',async()=>{const h=harness();await h.context.SiteOverviewUI.activate(h.pages[0]);h.fail();await assert.rejects(h.context.SiteOverviewUI.exportSnapshot(h.pages[0]),/최신/);assert.match(h.pages[0].nodes['[data-overview-status]'].textContent,/이전 집계/);});
