const {test}=require('node:test'),assert=require('node:assert/strict');
const O=require('../site-overview.js'),ExcelJS=require('../vendor/exceljs-4.4.0.min.js');
test('overview includes date-free steel confirmations and excludes hidden members without changing PRD dates',()=>{
 const model=O.summarize({steel:{items:[{key:'a',zone:'A3'},{key:'b',zone:'A3'},{key:'hidden',zone:'A3'}],records:{a:{installation_complete:true},b:{completed:'2026-10-01'},hidden:{installation_complete:true}},visibility:{hidden:{hidden:true}}},prd:{items:[{key:'p',zone:'A3'}],records:{p:{installation_complete:true}}}});
 assert.equal(model.trades[1].completed,2);assert.equal(model.trades[1].total,2);assert.equal(model.trades[1].percent,100);assert.equal(model.zones[0].trades[1].percent,100);assert.equal(model.trades[0].completed,0);
});
test('hidden steel members are excluded from overview and Excel totals while other trades stay intact',async()=>{const model=O.summarize({steel:{items:[{key:'hidden',zone:'A1'},{key:'active',zone:'A1'}],records:{hidden:{completed:'2026-10-02'}},visibility:{hidden:{hidden:true}}},slab:{items:[{key:'panel',zone:'A1'}],area:{gross:100,opening:20,total:80,completed:40,remaining:40,percent:50},areaByZone:{A1:{gross:100,opening:20,total:80,completed:40,remaining:40,percent:50}}}});assert.equal(model.trades[1].total,1);assert.equal(model.trades[1].completed,0);assert.equal(model.zones[0].trades[1].total,1);assert.equal(model.trades[2].completed,40);assert.equal(model.trades[2].unit,'m²');assert.equal(model.trades[2].percent,50);const round=new ExcelJS.Workbook();await round.xlsx.load(await O.build(ExcelJS,model).xlsx.writeBuffer());assert.equal(round.getWorksheet('공종별 현황').getCell('D5').value,1);assert.equal(round.getWorksheet('공종별 현황').getCell('E5').value,0);});
const sources={prd:{items:[{key:'p1',zone:'A1'},{key:'p2',zone:'B2'}],records:{p1:{drilled:'2026-09-01',installed:'2026-09-03'},orphan:{installed:'2026-09-02'}},zoneIds:['A1','A2','B2']},steel:{items:[{key:'b1',zone:'A1'},{key:'b1',zone:'A1'},{key:'b2',zone:'unassigned'}],records:{b1:{delivered:'2026-10-01'},b2:{completed:'2026-10-02'}}},slab:{items:[{key:'s',zone:'B2'}],records:{},area:{gross:100,opening:10,total:90,completed:0,remaining:90,percent:0},areaByZone:{B2:{gross:100,opening:10,total:90,completed:0,remaining:90,percent:0}}}};
test('progress counts registered unique items and each trade completion field, with independent zone denominators',()=>{const m=O.summarize(sources,'2026-10-02');assert.equal(m.trades[0].total,2);assert.equal(m.trades[0].completed,1);assert.equal(m.trades[0].previous,1);assert.equal(m.trades[1].total,2);assert.equal(m.trades[1].completed,1);assert.equal(m.trades[1].percent,50);assert.equal(m.trades[2].percent,0);assert.equal(m.zones.find(z=>z.id==='A1').trades[0].percent,100);assert.equal(m.zones.find(z=>z.id==='B2').trades[0].percent,0);assert.equal(m.zones.at(-1).id,'unassigned');assert.equal(m.overallPercent,undefined);});
test('unregistered data and empty registered zones are distinct from zero progress',()=>{const m=O.summarize(sources);assert.equal(m.trades[3].ready,false);assert.equal(m.trades[3].total,null);assert.equal(m.trades[3].percent,null);const empty=m.zones.find(z=>z.id==='A2').trades[0];assert.equal(empty.ready,true);assert.equal(empty.total,0);assert.equal(empty.percent,null);assert.equal(O.percent(100/4229),'0.02%');assert.ok(O.summarize({},'2026-10-02','north').trades.every(t=>!t.ready));});
test('overview XLSX round trip preserves counts and keeps unregistered curtain wall cells blank',async()=>{const m=O.summarize(sources,'2026-10-02'),book=O.build(ExcelJS,m),round=new ExcelJS.Workbook();await round.xlsx.load(await book.xlsx.writeBuffer());assert.deepEqual(round.worksheets.map(s=>s.name),['공종별 현황','공구별 현황']);const s=round.getWorksheet('공종별 현황');assert.equal(s.getCell('D4').value,2);assert.equal(s.getCell('E4').value,1);assert.equal(s.getCell('G4').value,.5);assert.equal(s.getCell('B7').value,'집계 준비 중');assert.equal(s.getCell('D7').value,null);assert.equal(s.getCell('G7').value,null);assert.equal(s.getCell('C6').value,'m²');assert.equal(s.getCell('D6').value,90);assert.equal(s.getCell('H6').value,100);assert.equal(s.getCell('I6').value,10);assert.equal(round.getWorksheet('공구별 현황').rowCount,3+4*m.zones.length);});

test('PRD completion caption is construction completion while slab still uses casting completion',()=>{assert.equal(O.trades[0].caption,'시공 완료');assert.equal(O.trades[2].caption,'타설 완료');});
